# Generated by Django 4.2.6 on 2023-10-23 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_name', models.CharField(max_length=100)),
                ('sales_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('account_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.record')),
            ],
        ),
    ]
