# Generated by Django 4.2.6 on 2023-10-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='quote_count',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
