# Generated by Django 4.2.6 on 2023-10-27 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0003_alter_record_customer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='primary_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Primary Rep'),
        ),
        migrations.AlterField(
            model_name='record',
            name='customer_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='website.accountlabel', verbose_name='Customer Type'),
        ),
    ]
