# Generated by Django 4.2.6 on 2023-10-27 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0005_alter_record_email_alter_record_primary_rep'),
    ]

    operations = [
        migrations.CreateModel(
            name='OppStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opp_name', models.CharField(max_length=50, verbose_name='Opp Name')),
                ('quote_amount', models.PositiveIntegerField(default=0, verbose_name='Quote Amount')),
                ('profit', models.PositiveIntegerField(default=0, verbose_name='Profit')),
                ('account_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='website.record', verbose_name='Account Name')),
                ('opp_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Opp Owner')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='website.oppstage', verbose_name='Stage')),
            ],
        ),
    ]
